name: Update search

on:
  # Run every night at 3:00 AM
  schedule:
    - cron: "0 3 * * *"

  # Allow manual trigger
  workflow_dispatch:

concurrency:
  group: update-search
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Docker command
        env:
          TYPESENSE_API_KEY: ${{ secrets.TYPESENSE_API_KEY }}
          TYPESENSE_HOST: 35n7gptj4h8z0dyop-1.a1.typesense.net
          TYPESENSE_PORT: 443
          TYPESENSE_PROTOCOL: https
        run: |
          CONFIG=$(cat config-umh.docs.json | jq -r tostring)
          docker run \
            -e "CONFIG=$CONFIG" \
            -e "TYPESENSE_API_KEY=${{ env.TYPESENSE_API_KEY }}" \
            -e "TYPESENSE_HOST=${{ env.TYPESENSE_HOST }}" \
            -e "TYPESENSE_PORT=${{ env.TYPESENSE_PORT }}" \
            -e "TYPESENSE_PROTOCOL=${{ env.TYPESENSE_PROTOCOL }}" \
            typesense/docsearch-scraper

